name: Build Eleventy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js current
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies \
        run: npm ci

      - name: Build TinaCMS
        env:
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
        run: npx tinacms build

      - name: Find ignore after tina
        run: find . -file ".gitignore" -print

      - name: Remove the .gitignore that Tina adds so it  deploys correctly
        run: | 
          rm -f \
            /docs/admin/.gitignore \
            /src/admin/.gitignore

      - name: Find ignore after rm
        run: find . -file "..gitignore" -print

      - name: Build 11ty
        run: npm run build

      - name: Find ignore after 11ty
        run: find . -file ".gitignore" -print


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir is the folder on the docker instance which eleventy builds the pages to.
          #it is not the docs folder in the repository
          publish_dir: docs
          #publish_branch is the branch in the repository.
          #this is where you need to point GitHub pages
          publish_branch: gh-pages